const { Guild } = require("discord.js");

const repliesNSFW =[
    "Did you ever had a sex dream? If yes what was it about ? ",
    "Do you have any fetishes?",
    "Have you ever sent out a nude Snapchat?",
    "Have you ever received a nude selfie? Who was it from? What was your reaction? Like or dislike?",
    "Describe the most attractive thing about each person in this chat.",
    "What is your wildest fantasy?",
    "How far would you go with someone you just met and will never see again?",
    "Rate me(here the person before) on a scale of 1 to 10, with 10 being the hottest.",
    "Would you choose a wild, hot relationship or a calm and stable one?",
    "What's your biggest turn-on?",
    "And your biggest turn-off?",
    "Would you go out with me(last person again) if I was the last person on earth?",
    "What's the sexiest thing about [fill in the name of a person in the chat(you can choose)]?",
    "If you could go on a romantic date with anyone in this chat, who would you pick?",
    "Have you ever flashed someone?",
    "Have you ever sexted anyone? And did you like it ? ;)",
    "Who is the sexiest person in this chat?",
    "Who has seen you without clothes on?",
    "Have you ever tried to take a sexy picture of yourself?",
    "Would you ever consider posing for Playboy?",
    "Did you ever had a sex dream? If yes what was it about ? ",
    "Have you ever been to a nudist beach? Would you consider going?",
    "Have you ever seen a naughty magazine?",
    "What's the sexiest thing about a guy?",
    "What's the sexiest thing about a girl?",
    "Have you ever sent a nude selfie? Who would you send it to in the chat and outside?",
    "Who do you most want to sleep with, out of everyone here?",
    "Have you ever been attracted to the same sex?",
    "When and where was your first kiss? Who was it with?",
    "When did you lose your virginity, and to whom did you lose it?",
    "What's your ultimate sexual fantasy?",
    "What do you do to get yourself 'sexy'?",
    "Would you go out with an older guy/girl? How old is too old?",
    "Do you sleep in the nude?",
    "How much money would we have to pay you for you to agree to flash your boobs?",
    "Have you ever been in a 'friends with benefits' situation?",
    "If you had to go skinny dipping with someone, who in this chat would you choose?",
    "If I paid you $100, would you wear your sexiest clothes to class?",
    "If you got to have a threesome with people in this chat, who would you do it with and why?",
    "Have you ever sexted anyone? If so, read one of the sexts in a fake British accent.",
    "What is the most adventurous thing you’d want someone to do to you?",
    "What is the song that you get it on to the most?",
    "Where are you on the straight / queer spectrum? Be honest!",
    "What’s your favorite fantasy to pleasure yourself to?",
    "Where is the weirdest place that you’ve ever masturbated?",
    "What is your favorite 'special' toy?",
    "When was the first time you came?",
    "Who was your best partner and why?",
    "When was your first kiss?",
    "Do you have an “I’m getting laid tonight” outfit? What it is?",
    "Who’s the hottest person at work/school?",
    "What would be more thrilling: angry sex or make-up sex?",
    "What’s the worst kiss you’ve ever been given?",
    "What’s something romantic you’ve done that you’re most proud of?",
    "How often are you horny?💢",
    "Have you ever been caught masturbating?",
    "How often are you masturbating?",
    "Ideal Sex Position?",
    "How do you masturbate?",
    "Have you ever seen someone naked? Per accident or etc.?",
    "Bra/Dick Size",
    "Pubic Hair how is it for you?",
    "Most embarrasing sexual story",
    "Have you ever considered a threesome?",
    "Do you have any interesting fetishes?",
    "Have you ever been to a strip club?",
    "When did you masturbate for the first time?",
    "What was the most powerful sexual experience you’ve ever had?",
    "Give your junk a name",
    "Most embarrassing time you got turned on?",
    "Ever wanted to try on women’s clothing?",
    "What is the dumbest thing you’ve ever done?",
    "Strangest off-limits crush?",
    "Have you ever made someone cry?",
    "What is the craziest thing you’ve ever watched?(Porn like)",
    "What is one thing you’ve never done in the bedroom?",
    "Have you ever done it in a car?",
    "Have you ever given or been given ‘attention’ while driving a car?",
    "When it comes to lingerie, is less best, or leave something to unwrap?",
    "Have you ever role played?",
    "What’s the worst lie you’ve ever told?",
    "What’s your worst substance story (getting drunk, high, etc.)?",
    "Do you have any spicy pictures or videos saved on your phone?",
    "Send the most recent text that you sent your best friend.",
    "Write a 100-word naughty story and send it in the chat.",
    "What are you wearing?",
    "What’s your worst fart story?",
    "What did you think of me when you first met me?",
    "When was your sexual awakening?",
    "Who do Iremind you of?",
    "Are you turned on right now?",
    "Do you want to be tied up?",
    "What was your funniest sexual experience like?",
    "Have you ever done it in a public place? Like Abbey :)",
    "Who’s the ex you’d do again in a heartbeat?",
    "Do you have a hot cousin?",
    "Hottest thing someone’s ever done to you?",
    "Do you think your parents are hot?",
    "Fill in the blanks: I would pay $1,000 to have X do X to me.",
    "Do you prefer to have a dominant, submissive, or neutral partner? Explain why?",
    "How was your first sex experience?",
    "How was your first same sex experience?",
    "Have you ever experimented with someone of the same sex?",
    "What are the sexiest things someone has said to you?",
    "Does naughty talk get you aroused?",
    "Have you ever faked an orgasm?",
    "Would you rather give or receive pleasure?",
    "Have you ever fantasized about a teacher?",
    "What’s a sexual act you’ll never do?",
    "What’s the dirtiest thing you have been caught doing ?",
    "Do you like sex to be rough or sensual?",
    "What was your most embarrassing situation while in bed?",
    "Who gave you your first orgasm?",
    "Have you ever been friend-zoned? If so, by whom?",
    "What excites you the most?",
    "What is your favorite type of porn?",
    "Have you ever masturbated in a public space?",
    "What are your dirtiest secrets?",
    "Have you ever tried anal sex? Or thought about it?",
    "Who in this chat would you most want to see naked?",
    "Describe the underwear you're wearing right now.",
    "Name a celebrity you've had a sexual fantasy about.",
    "Have you ever walked in on people having sex?",
    "Tell us your most awkward sex dream.",
    "Tell us the hottest sex dream you've ever had.",
    "Have you ever taken nudes?",
    "Have you ever recorded yourself having sex/ or masturbating?",
    "Which would you rather give up for a year: sex or alcohol?",
    "Which would you rather give up for a year: partner sex or masturbation?",
    "Have you ever had sex in a car? (Like next to a church 😏)",
    "What's the highest number of orgasms you've had in a day?",
    "Would you rather have sex with someone 10 years older or 5 years younger?",
    "What’s a popular fetish that you would never want to try?",
    "If you could have one sexual superpower, what would it be?",
    "Do you think virginity is special?",
    "Who is the oddest person you’ve ever had a sexual fantasy about?",
    "Do you think there’s an age where someone becomes “too old” to be a virgin?",
    "Who in the chat do you think has slept with the most people?",
    "Do you think there should be a limit on the amount of people you sleep with in your lifetime or do you think that doesn’t matter?",
    "Have you ever called someone “Daddy” or been called “Daddy” while having sex?",
    "What fictional character have you or could you have sexual fantasies about?",
    "Are you a fan of foreplay?",
    "Are you a fan of shower sex?",
    "When’s the last time you pleasured yourself?",
    "Do you enjoy receiving nudes?",
    "Tell me about the best orgasm you’ve ever had.",
    "Have you ever watched or wanted to watch another couple have sex?",
    "Lights off or lights on during sex?",
    "Where is your favorite place to have sex?",
    "Does dirty talk get you horny?",
    "What’s the quickest way to get you into bed?",
    "Do you prefer a little hair or smooth-shaven?",
    "If I was with you right now, what would you want to do to me?",
    "If I was with you right now, what would you want me to do to you?",
    "Have you ever had phone sex before?",
    "How can I get you horny?",
    "Have you ever done something that you feel guilty about?",
    "If I went through your room, would I find anything hidden or interesting?",
    "Do you have a name for your penis or vagina?",
    "Ever played seven minutes in heaven ? If yes what happened?",
    "Favorite way of masturbating",
    "How do you masturbate?",
    "Ever tasted your own semen?",
    "What is the longest you've ever given head?",
    `How do you feel about sex in groups?`,
    `Would you ever watch your partner have sex with someone else?`,
    `Describe how you orgasim feels?`,
    `Where is your favourite place to be kissed?`,
    `Have you ever taken it in the butt or would you?`,
    `What is the longest time you’ve gone without sex?`,
    `Have you ever paid for sex?`,
    `Have you ever performed oral on someone of the same sex?`,
    `Have you ever made a video of yourself?(nsfw-ise)`,
    `Who is your favourite porn star?`,
    `Have you ever thought about being a stripper?`,
    `Does size matter?`,
    `Do you prefer to have music in the background, or for it to be be quiet?`,
    `Do you prefer for your partner to be silent, or do you like moans?`,
    `What is your “sweet spot”?`,
    `Would you ever have sex for money?`,
    `How flexible are you?`,
    `Spit or Swallow?`,
    `Did you smoke or drink before college? Or did you start when you got here?`,
    `Have you ever slept with your roommate’s bf/gf?`,
    `Have you ever had sex in your parent’s bed?`,
    `Have you ever wanted to have an orgy?`,
    `What is most amount of shots that you have taken in one night?`,
    `Have you ever gotten an STD?`,
    `Have you ever woken up to a stranger in your bed?`,
    `How many freshmen have you slept with?`,
    `Have you ever done a sex train?`,
    `Would you ever want to go to a swingers party?`,
    `Do you like “doggy-style” or “missionary” better?`,
    `When and where did you last have sex?`,
    `What’s your secret talent in bed?`,
    `What does it take for you to have an one-night stand?`,
    `Would you rather have sex on the first date or just a romantic kiss at the end?`,
    `Point out a co-player in this chat you would do it with right now.`,
    `Name 2 sexual things you’re not into.`,
    `Tell an erotic story about yourself or one of your friends.`,
    `Dominant or submissive?`,
    `What is the best time of day to have sex?`,
    `Tell the group about your last one-night stand.`,
    `“It turns me on when somebody calls me …..” during sex.`,
    `You’re the flirt expert. Give 3 good tips.`,
    `. What’s the least amount of time you’ve known someone before you’ve had sex with them?`,
    `Who is the most inappropriate person you’ve had a sexual fantasy about?`,
    `What’s a sex act most people like that you think is overrated?`,
    `If you had to choose between only oral sex or only penetrative sex for the rest of your life, which one would you pick?`,
    `Is sex better when you’re in love, or better when the other person is hot and mysterious?`,
    `What is the largest age gap you’ve had between you and someone you’ve had sex with?`,
    `What’s #1 on your sexual bucket list right now?`,
    `Have you ever taken someone’s virginity?`,
    `Would you rather dominate someone or be dominated?`,
    `What do you think is the sexiest body part of the opposite sex?`,
    `What do you think is the sexiest body part of your same sex?`,
    `What’s something most people don’t like in bed, but you can’t get enough of?`,
    `If you had the power to give or receive unlimited orgasms, what would you pick?`,
    `If you had to fuck one animal, what animal would you pick?`,
    `How old do you think is “too old” for someone to still be a virgin?`,
    `What is a somewhat weird fetish that you would actually try?`,
    `What’s the first thing you’d do if you could inhabit the body of the opposite sex for one hour?`,
    `What’s the weirdest thing you’ve ever done while masturbating?`,
    `If you had to choose between having sex with one person for the rest of your life or never being able to have sex with the same person more than once, what would you pick?`,
    ` Would you rather pay someone to put on a striptease for you (they aren’t allowed to touch), pay someone to cuddle and massage you while wearing non-sexy clothes, or pay someone to talk dirty over the phone but never be able to see them?`,
    `What’s the least sexual thing that has gotten you aroused?`,
    `If you were forced to have sex with someone in your extended family, who would you pick?`,
    `What’s a common fetish that you would never try in real life?`,
    `What do you wish someone would have told you about sex way earlier?`,
    `Have you ever kicked someone out of your bed immediately after having sex?`,
    `What one sexual experience would you want to erase from your memory?`,
    `Have you ever called someone (or been called) ‘Daddy’?`,
    `What one sexual experience do you think about most often?`,
    `Would you rather spank someone or be spanked?`,
    ` If you could double the amount in your bank account or double the amount of sexual partners you’ve had, which would you pick?`,
    `Would you rather sleep with only insanely hot people or sleep with only people who think you’re insanely hot?`,
    `How much money would your boss have to offer you before you slept with him or her?`,
    `Do you have any sex tapes?`,
    ` What’s the most public place you’d fuck someone?`,
    `Do you like giving or receiving a lap dance?`,
    `Tell me about the time you lost your virginity.`,
    `Are you apart of the mile high club? (Have you had sex in an airplane or hot air balloon?)`,
    `Who triggered your sexual awakening?`,
    `How many people in this chat would you masturbate to`,
    `Would you rather have penis length nipples or a nipple length penis?`,
    `If O.P's friend's girlfriend and mom's (girlfriend can be switched with crush or hot girl in the room) were inflicted with a curse which switched their souls (like Freaky Friday) and the only way to reverse it was to have sex with one of them, who would it be? It'd basically be like would you rather have sex with your girlfriend in your mom's body or have sex with your mom in your girlfriends body.`,
    `If a snake bit me on the tip of my penis and I was going to die if you didn't suck the poison out would you do it?`,
    `Kill, Fuck, Marry (only chat/server)`,
    `What is the largest object that has ever been in your Rectum ?`,
    `If you had to flash a person in this chat, who would it be?`,
    `Have you ever received a nude from someone you knew but weren’t interested in?`,
    `How many times have you thought you were pregnant?`,
    `Have you ever masturbated at a friends house?`,
    `Have you ever masturbated at work?`,
    `What question are you hoping I won't ask?`,
    `Would you rather fuck a goat and have nobody ever find out, or not have to fuck a goat but have everyone think that you did.`,
    `who would you turn gay for?`,
    `Have you ever had sexual thoughts or dreams about anyone in the room.`,
    `The last time your masturbated what did you watch or what were you thinking about?`,
    `I dare you to kiss the prettiest girl in the room on the lips. Jokes aside this is a fun question 259. The real question is Your father or mother switches bodies with your girlfriend or boyfriend. The only way to switch them back is to have sex with either your partner in your parent's body, or vice versa. Which do you choose.`,
    `Have you ever peed in a pool full of people?`,
    `If you had to kiss one of the players, who would it be?`,
    `Have you ever fallen in love with a friend of your partner and did anyone notice?`,
    `What’s the dirtiest thought you’ve ever had?`,
    `Have you ever sent a nude selfie or if not, who would you send one to?`,
    `At what age did you first start having sexy thoughts and what prompted them?`,
    `What three adjectives best describe your private parts?`,
    `hat does the perfect male/female body look like (from head to toe and everything in-between) in your opinion?`,
    `What would you guess is your parents’ favorite sexual position and why?`,
    `What did you think about the first (or last) time you masturbated?`,
    `What’s your self-love strategy?`,
    `What’s the most awkward experience you’ve had with a crush?`,
    `How do you really feel about anal sex?`,
    `How do you like the taste when you go down on someone?`,
    `What’s your favorite sex toy (hypothetically or from experience)?`,
    `Do you have any spicy pictures or videos saved on your phone?`,
    `Do you have a name for your special places?`,
    `Where did you get your attractive face from, your parents or grandparents?`,
    `How far would you go with someone you just met and will never see again?`,
    `If I looked in your nightstand/under your bed, what would I find?`,
    `What would you buy me if I gave you fifty dollars?`,
    `If I was a food, what would I be and how would you eat me?`,
    `When did you watch adults-only movies for the first time?`,
    `Do you trim down there?`,
    `Would you go out with me if I was the last person on earth?(next to you)`,
    `How would you rate your own looks on a scale of one to ten?`,
    `Have you ever been caught checking someone out?`,
    `If I gave you a chance to touch one of my body parts, which part you would choose?`,
    `Have you ever received any love letters and if yes, read them aloud.`,
    `Tell us five secrets of yours.`,
    `How many hours would you spend online if you didn’t have school or homework?`,
    `Do you prefer a masseuse of the opposite gender or the same?`,
    `Tell something you were always afraid to express.`,
    `Will you allow me to check the browsing history on your mobile?`,
    `Did you ever accidentally send a wrong intimate message to your colleague?`,
    `Have you ever accidentally grabbed someones butt?`,
    `Have you ever seen animals reproducing?`,
    `Have you ever had to hump anything? If you had to, what did you hump?`,
    `Of the people in this room, who do you consider the sluttiest?`,
    `Of the people in this room, who would you feel most comfortable with naked?`,
    `At what age did you first inspect your private parts and how did you feel about them?`,
    `What’s the grossest thing that’s come out of your body?`,
    `What time of day do you feel most aroused and what do you usually do about it?`,
    `Do you ever catch yourself thinking about doing it with someone of the same sex?`,
    `How old were you when your parents sat you down for “the talk” and what did they say (or not say) about “the birds and the bees”?`,
    `What’s the most number of times you’ve ever masturbated within one week?`,
    `Did you masturbate today ? If yes how long was it ago ?`,
];
module.exports = function(msg, args){
    const index = Math.floor(Math.random() * repliesNSFW.length);
    msg.channel.send(repliesNSFW[index]);
};