const { Guild } = require("discord.js");

const repliesNSFW =[
    "Did you ever had a sex dream? If yes what was it about ? ",
    "Do you have any fetishes?",
    "Have you ever sent out a nude Snapchat?",
    "Have you ever received a nude selfie? Who was it from? What was your reaction? Like or dislike?",
    "Describe the most attractive thing about each person in this chat.",
    "What is your wildest fantasy?",
    "How far would you go with someone you just met and will never see again?",
    "Rate me(here the person before) on a scale of 1 to 10, with 10 being the hottest.",
    "Would you choose a wild, hot relationship or a calm and stable one?",
    "What's your biggest turn-on?",
    "And your biggest turn-off?",
    "Would you go out with me(last person again) if I was the last person on earth?",
    "What's the sexiest thing about [fill in the name of a person in the chat(you can choose)]?",
    "If you could go on a romantic date with anyone in this chat, who would you pick?",
    "Have you ever flashed someone?",
    "Have you ever sexted anyone? And did you like it ? ;)",
    "Who has seen you without clothes on?",
    "Would you ever consider posing for Playboy?",
    "Have you ever been to a nudist beach? Would you consider going?",
    "Have you ever seen a naughty magazine?",
    "Have you ever sent a nude selfie? Who would you send it to in the chat and outside?",
    "Who do you most want to sleep with, out of everyone here?",
    "Have you ever been attracted to the same sex?",
    "When and where was your first kiss? Who was it with?",
    "When did you lose your virginity, and to whom did you lose it?",
    "What's your ultimate sexual fantasy?",
    "Would you go out with an older guy/girl? How old is too old?",
    "Do you sleep in the nude?",
    "How much money would we have to pay you for you to agree to flash your boobs?",
    "Have you ever been in a 'friends with benefits' situation?",
    "If you had to go skinny dipping with someone, who in this chat would you choose?",
    "If I paid you $100, would you wear your sexiest clothes to class?",
    "If you got to have a threesome with people in this chat, who would you do it with and why?",
    "Have you ever sexted anyone? If so, read one of the sexts in a fake British accent.",
    "What is the most adventurous thing you’d want someone to do to you?",
    "What is the song that you get it on to the most?",
    "Where are you on the straight / queer spectrum? Be honest!",
    "What’s your favorite fantasy to pleasure yourself to?",
    "Where is the weirdest place that you’ve ever gone solo?",
    "What is your favorite 'special' toy?",
    "When was the first time you came?",
    "Who was your best partner and why?",
    "When was your first kiss?",
    "Do you have an “I’m getting laid tonight” outfit? What it is?",
    "Who’s the hottest person at work/school?",
    "What would be more thrilling: angry sex or make-up sex?",
    "What’s the worst kiss you’ve ever been given?",
    "What’s something romantic you’ve done that you’re most proud of?",
    "How often are you horny?💢",
    "Have you ever been caught masturbating?",
    "How often are you masturbating?",
    "Ideal Sex Position?",
    "How do you masturbate?",
    "Have you ever seen someone naked? Per accident or etc.?",
    "Bra/Dick Size",
    "Pubic Hair how is it for you?",
    "Most embarrasing sexual story",
    "Have you ever considered a threesome?",
    "Do you have any interesting fetishes?",
    "Have you ever been to a strip club?",
    "When did you go solo for the first time?",
    "What was the most powerful sexual experience you’ve ever had?",
    "Give your junk a name",
    "Most embarrassing time you got turned on?",
    "Ever wanted to try on women’s clothing?",
    "What is the dumbest thing you’ve ever done?",
    "Strangest off-limits crush?",
    "Have you ever made someone cry?",
    "What is the craziest thing you’ve ever watched?(Porn like)",
    "What is one thing you’ve never done in the bedroom?",
    "Have you ever done it in a car?",
    "Have you ever given or been given ‘attention’ while driving a car?",
    "When it comes to lingerie, is less best, or leave something to unwrap?",
    "Have you ever role played?",
    "What’s the worst lie you’ve ever told?",
    "What’s your worst substance story (getting drunk, high, etc.)?",
    "Do you have any spicy pictures or videos saved on your phone?",
    "Send the most recent text that you sent your best friend.",
    "Write a 100-word naughty story and send it in the chat.",
    "What are you wearing?",
    "What’s your worst fart story?",
    "What did you think of me when you first met me?",
    "When was your sexual awakening?",
    "Who do Iremind you of?",
    "Are you turned on right now?",
    "Do you want to be tied up?",
    "What was your funniest sexual experience like?",
    "Have you ever done it in a public place? Like Abbey :)",
    "Who’s the ex you’d do again in a heartbeat?",
    "Do you have a hot cousin?",
    "Hottest thing someone’s ever done to you?",
    "Do you think your parents are hot?",
    "Fill in the blanks: I would pay $1,000 to have X do X to me.",
    "Do you prefer to have a dominant, submissive, or neutral partner? Explain why?",
    "How was your first sex experience?",
    "How was your first same sex experience?",
    "Have you ever experimented with someone of the same sex?",
    "What are the sexiest things someone has said to you?",
    "Does naughty talk get you aroused?",
    "Have you ever faked an orgasm?",
    "Would you rather give or receive pleasure?",
    "Have you ever fantasized about a teacher?",
    "What’s a sexual act you’ll never do?",
    "What’s the dirtiest thing you have been caught doing ?",
    "Do you like sex to be rough or sensual?",
    "What was your most embarrassing situation while in bed?",
    "Who gave you your first orgasm?",
    "Have you ever been friend-zoned? If so, by whom?",
    "What excites you the most?",
    "What is your favorite type of porn?",
    "Have you ever masturbated in a public space?",
    "What are your dirtiest secrets?",
    "Have you ever tried anal sex? Or thought about it?",
    "Who in this chat would you most want to see naked?",
    "Describe the underwear you're wearing right now.",
    "Name a celebrity you've had a sexual fantasy about.",
    "Have you ever walked in on people having sex?",
    "Tell us your most awkward sex dream.",
    "Tell us the hottest sex dream you've ever had.",
    "Have you ever taken nudes?",
    "Have you ever recorded yourself having sex/ or masturbating?",
    "Which would you rather give up for a year: sex or alcohol?",
    "Which would you rather give up for a year: partner sex or masturbation?",
    "Have you ever had sex in a car? (Like next to a church 😏)",
    "What's the highest number of orgasms you've had in a day?",
    "Would you rather have sex with someone 10 years older or 5 years younger?",
    "What’s a popular fetish that you would never want to try?",
    "If you could have one sexual superpower, what would it be?",
    "Do you think virginity is special?",
    "Who is the oddest person you’ve ever had a sexual fantasy about?",
    "Do you think there’s an age where someone becomes “too old” to be a virgin?",
    "Who in the chat do you think has slept with the most people?",
    "Do you think there should be a limit on the amount of people you sleep with in your lifetime or do you think that doesn’t matter?",
    "Have you ever called someone “Daddy” or been called “Daddy” while having sex?",
    "What fictional character have you or could you have sexual fantasies about?",
    "Are you a fan of foreplay?",
    "Are you a fan of shower sex?",
    "When’s the last time you pleasured yourself?",
    "Do you enjoy receiving nudes?",
    "Tell me about the best orgasm you’ve ever had.",
    "Have you ever watched or wanted to watch another couple have sex?",
    "Lights off or lights on during sex?",
    "Where is your favorite place to have sex?",
    "Does dirty talk get you horny?",
    "What’s the quickest way to get you into bed?",
    "Do you prefer a little hair or smooth-shaven?",
    "If I was with you right now, what would you want to do to me?",
    "If I was with you right now, what would you want me to do to you?",
    "Have you ever had phone sex before?",
    "How can I get you horny?",
    "Have you ever done something that you feel guilty about?",
    "If I went through your room, would I find anything hidden or interesting?",
    "Do you have a name for your penis or vagina?",
    "Ever played seven minutes in heaven ? If yes what happened?",

];
module.exports = function(msg, args){
    const index = Math.floor(Math.random() * repliesNSFW.length);
    msg.channel.send(repliesNSFW[index]);
};