const repliesPasta=[
`What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.`,
`Hummina hummina hummina bazooooooooing! *eyes pop out* AROOOOOOOOGA! *jaw drops tongue rolls out* WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF *tongue bursts out of the outh uncontrollably leaking face and everything in reach* WURBLWUBRLBWURblrwurblwurlbrwubrlwburlwbruwrlblwublr *tiny cupid shoots an arrow through heart* Ahhhhhhhhhhh me lady... *heart in the shape of a heart starts beating so hard you can see it through shirt* ba-bum ba-bum ba-bum ba-bum ba-bum *milk truck crashes into a bakery store in the background spiling white liquid and dough on the streets* BABY WANTS TO FUCK *inhales from the gas tank* honka honka honka honka *masturabtes furiously* ohhhh my gooooodd~`,
`"Oh I'm sorry. I just looked at your profile I didn't realize you where a lady. (And a beautiful one at that) I try my best to respect women. Especially women in gaming. As a matter of fact now I actually do agree with you. I'm sorry. Maybe you could even add me on PSN and we can play some games together. We could play GTA, overwatch, Minecraft, maybe even a little COD. add me xXxChildMolesterxXx. Sorry about my name. My cousin made it a while back. He is not a good person like me and does not carry my values.
Good day ma'am.
Also I PM'd you. Take a look and lmk what you think.`,
"hey, sorry I saw your profile and I just thought you looked cute in your picture, I really wanted to tell you that)) It's really rare to see girls playing video games haha! I don't know why its a guy thing honestly im like really against misogyny and like ill be the one in the kitchen making sandwiches. We should really play l4d2 sometime its a really cool zombie game with a lot of scary moments, but don't worry ill be there to protect you ;) sorry that wasnt flirting I swear Im just trying to be friendly I really like your profile picture sorry was that too far? Really sorry i'm really shy I don't go out much haha add me on skype we should talk more you look really nice and fun xxx",
"I have an IQ in the high 130s. Tread fucking lightly with that tone. You would be my subordinate in ANY situation. Be thankful you found this girl and don't let her be alone any longer. She shouldn't be alone. None of these women should be alone.",
"You have made a massive mistake. Doing this for me would have made you a symbol in the world of intellect and literature. It is so typical for someone like you to forget this. It is so typical for someone like you to use abbreviated words. I was prepared to open your world to my knowledge and share my stories and art, with you. You will forever regret the choice you just made, so I will offer to let you do this project again. If you do not, you will have to face the consequences.",
"Quit gaming 6 months ago. Bought a new car, I have an amazing new girlfriend, I make a shitload of money and I'm buying a house this spring. I party every weekend, I'm never home. I'm enjoying life. Do yourselves a favor. Stop trying to make gaming a career. It's cringe as fuck.",
//`Dicks are so cute omg( •?• ) when you hold one in your hand and it starts twitching its like its nuzzling you(/) or when they perk up and look at you like" owo nya? :3c" hehe ~ penis-kun is happy to see me!!(?) and the most adorable thing ever is when sperm-sama comes out but theyre rlly shy so u have to work hard!!(?••) but when penis-kun and sperm-sama meet and theyre blushing and all like "uwaaa~!" (?´?)?: ?hehehe~penis-kun is so adorable (?´???)?::?`,
`A Marine was taking college classes between his deployments to Afghanistan.

One of his courses had a professor that was an atheist and a member of the ACLU. One day the professor shocked everyone by walking into class, looking up and stating "God, if you are real, I want you to come down and knock me off this platform, I will give you 15 minutes.

Several minutes tick by in silence, when the 15 min. time almost expired the Marine gets up from his seat, approaches the professor and punched him in the face knocking him off the platform and out cold. The Marine simply went back to his seat.

The professor came to, visibly shaken and asked the Marine, "What the heck did you do that for?!"

The Marine said, "God was busy protecting America's military who are out protecting your right to say stupid shit like that, so he sent me to fill in."`,
`少年，你太年轻了。你以为这个论坛上真的有那么多人回复你的帖子？其实都是我一个人回的，不然我换个ID发同样的话给你看。

Son, you’re too young. Do you really think there are that many people responding to your post on this forum? It was all me. Let me change another user ID again and post the same expression here, then you’ll know.`
];
module.exports = function(msg, args){
    const index = Math.floor(Math.random() * repliesPasta.length);
    msg.channel.send(repliesPasta[index]);
}